main:tcpclient.c tcpserver.c ../common/common.c
	gcc -Wall -o client.out tcpclient.c ../common/common.c
	gcc -Wall -o server.out tcpserver.c ../common/common.c
	
nowarn:tcpclient.c tcpserver.c ../common/common.c
	gcc -o client.out tcpclient.c ../common/common.c
	gcc -o server.out tcpserver.c ../common/common.c	
	
clean:
	rm *.out
