main:tcpclient.c ../../common/common.c
	gcc -Wall -o client.out tcpclient.c ../../common/common.c
	
nowarn:tcpclient.c ../../common/common.c
	gcc -o client.out tcpclient.c ../../common/common.c
	
clean:
	rm *.out
