main:tcpclient.c tcpserver.c
	gcc -Wall -o client.out tcpclient.c
	gcc -Wall -o server.out tcpserver.c
	
nowarn:tcpclient.c tcpserver.c
	gcc -o client.out tcpclient.c
	gcc -o server.out tcpserver.c	
	
clean:
	rm *.out
