#!/bin/sh
defaultname = "09 hello"

basepath=$(cd `dirname $0`; pwd)

prefix=${1}

if [ "$prefix" =  "" ] 
then
prefix = ${defaultname}
fi



testkernlog= ${prefix}"_serv_kern"
export testkernlog

/usr/bin/make

./server.out > ${prefix}"_server" &
/bin/echo > /var/log/kern.log
./rawtest.out > ${prefix}"_client"



