main:
	gcc -D_REENTRANT -Wall -o rawtest.out testraw.c ../../common/common.c ../../common/rawops.c -lpthread

nowarn:
	gcc -D_REENTRANT -o rawtest.out testraw.c ../../common/common.c ../../common/rawops.c -lpthread
	
clean:
	rm *.out
	
