main:tcpclient01.c tcpclient02.c ../common/common.c
	gcc -Wall -o tcpclient01.out tcpclient01.c ../common/common.c
	gcc -Wall -o tcpclient02.out tcpclient02.c ../common/common.c
	
nowarn:tcpclient01.c tcpclient02.c ../common/common.c
	gcc -o tcpclient01.out tcpclient01.c ../common/common.c
	gcc -o tcpclient02.out tcpclient02.c ../common/common.c

clean:
	rm *.out
copy:
	cp tcpclient01.c tcpclient02.c
